// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.6
// source: varify.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VarifyService_GetVarifyCode_FullMethodName = "/varify.VarifyService/GetVarifyCode"
)

// VarifyServiceClient is the client API for VarifyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VarifyServiceClient interface {
	GetVarifyCode(ctx context.Context, in *GetVarifyCodeRequest, opts ...grpc.CallOption) (*GetVarifyCodeResponse, error)
}

type varifyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVarifyServiceClient(cc grpc.ClientConnInterface) VarifyServiceClient {
	return &varifyServiceClient{cc}
}

func (c *varifyServiceClient) GetVarifyCode(ctx context.Context, in *GetVarifyCodeRequest, opts ...grpc.CallOption) (*GetVarifyCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVarifyCodeResponse)
	err := c.cc.Invoke(ctx, VarifyService_GetVarifyCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VarifyServiceServer is the server API for VarifyService service.
// All implementations must embed UnimplementedVarifyServiceServer
// for forward compatibility.
type VarifyServiceServer interface {
	GetVarifyCode(context.Context, *GetVarifyCodeRequest) (*GetVarifyCodeResponse, error)
	mustEmbedUnimplementedVarifyServiceServer()
}

// UnimplementedVarifyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVarifyServiceServer struct{}

func (UnimplementedVarifyServiceServer) GetVarifyCode(context.Context, *GetVarifyCodeRequest) (*GetVarifyCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVarifyCode not implemented")
}
func (UnimplementedVarifyServiceServer) mustEmbedUnimplementedVarifyServiceServer() {}
func (UnimplementedVarifyServiceServer) testEmbeddedByValue()                       {}

// UnsafeVarifyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VarifyServiceServer will
// result in compilation errors.
type UnsafeVarifyServiceServer interface {
	mustEmbedUnimplementedVarifyServiceServer()
}

func RegisterVarifyServiceServer(s grpc.ServiceRegistrar, srv VarifyServiceServer) {
	// If the following call pancis, it indicates UnimplementedVarifyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VarifyService_ServiceDesc, srv)
}

func _VarifyService_GetVarifyCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVarifyCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VarifyServiceServer).GetVarifyCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VarifyService_GetVarifyCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VarifyServiceServer).GetVarifyCode(ctx, req.(*GetVarifyCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VarifyService_ServiceDesc is the grpc.ServiceDesc for VarifyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VarifyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "varify.VarifyService",
	HandlerType: (*VarifyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVarifyCode",
			Handler:    _VarifyService_GetVarifyCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "varify.proto",
}
