// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: msg.proto

#include "msg.pb.h"
#include "msg.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace msg {

static const char* LogicService_method_names[] = {
  "/msg.LogicService/Handle",
};

std::unique_ptr< LogicService::Stub> LogicService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< LogicService::Stub> stub(new LogicService::Stub(channel, options));
  return stub;
}

LogicService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Handle_(LogicService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status LogicService::Stub::Handle(::grpc::ClientContext* context, const ::msg::ProtoReq& request, ::msg::ProtoResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::msg::ProtoReq, ::msg::ProtoResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Handle_, context, request, response);
}

void LogicService::Stub::async::Handle(::grpc::ClientContext* context, const ::msg::ProtoReq* request, ::msg::ProtoResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::msg::ProtoReq, ::msg::ProtoResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Handle_, context, request, response, std::move(f));
}

void LogicService::Stub::async::Handle(::grpc::ClientContext* context, const ::msg::ProtoReq* request, ::msg::ProtoResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Handle_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::msg::ProtoResp>* LogicService::Stub::PrepareAsyncHandleRaw(::grpc::ClientContext* context, const ::msg::ProtoReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::msg::ProtoResp, ::msg::ProtoReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Handle_, context, request);
}

::grpc::ClientAsyncResponseReader< ::msg::ProtoResp>* LogicService::Stub::AsyncHandleRaw(::grpc::ClientContext* context, const ::msg::ProtoReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHandleRaw(context, request, cq);
  result->StartCall();
  return result;
}

LogicService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LogicService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LogicService::Service, ::msg::ProtoReq, ::msg::ProtoResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LogicService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::msg::ProtoReq* req,
             ::msg::ProtoResp* resp) {
               return service->Handle(ctx, req, resp);
             }, this)));
}

LogicService::Service::~Service() {
}

::grpc::Status LogicService::Service::Handle(::grpc::ServerContext* context, const ::msg::ProtoReq* request, ::msg::ProtoResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace msg

