// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: push.proto
#ifndef GRPC_push_2eproto__INCLUDED
#define GRPC_push_2eproto__INCLUDED

#include "push.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace push {

//   client  -------------------
//     |                   ^
//     | ProtoReq          |
//     |                   | ProtoResp
//     V                   |
//  msg_gate -------------------
//     |                   ^
//     | ProtoReq          |
//     |                   | ProtoResp
//     V                   |
//  msg_gate -------------------
//     |
//     | MqMessage
//     |
//     V
//   Kafka
//     |
//     | MqMessage
//     |
//     V
//  transfer
//     |
//     | PushReq
//     |
//     V
class PushService final {
 public:
  static constexpr char const* service_full_name() {
    return "push.PushService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Push(::grpc::ClientContext* context, const ::msg::PushReq& request, ::msg::PushResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::msg::PushResp>> AsyncPush(::grpc::ClientContext* context, const ::msg::PushReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::msg::PushResp>>(AsyncPushRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::msg::PushResp>> PrepareAsyncPush(::grpc::ClientContext* context, const ::msg::PushReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::msg::PushResp>>(PrepareAsyncPushRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Push(::grpc::ClientContext* context, const ::msg::PushReq* request, ::msg::PushResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Push(::grpc::ClientContext* context, const ::msg::PushReq* request, ::msg::PushResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::msg::PushResp>* AsyncPushRaw(::grpc::ClientContext* context, const ::msg::PushReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::msg::PushResp>* PrepareAsyncPushRaw(::grpc::ClientContext* context, const ::msg::PushReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Push(::grpc::ClientContext* context, const ::msg::PushReq& request, ::msg::PushResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::msg::PushResp>> AsyncPush(::grpc::ClientContext* context, const ::msg::PushReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::msg::PushResp>>(AsyncPushRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::msg::PushResp>> PrepareAsyncPush(::grpc::ClientContext* context, const ::msg::PushReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::msg::PushResp>>(PrepareAsyncPushRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Push(::grpc::ClientContext* context, const ::msg::PushReq* request, ::msg::PushResp* response, std::function<void(::grpc::Status)>) override;
      void Push(::grpc::ClientContext* context, const ::msg::PushReq* request, ::msg::PushResp* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::msg::PushResp>* AsyncPushRaw(::grpc::ClientContext* context, const ::msg::PushReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::msg::PushResp>* PrepareAsyncPushRaw(::grpc::ClientContext* context, const ::msg::PushReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Push_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Push(::grpc::ServerContext* context, const ::msg::PushReq* request, ::msg::PushResp* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Push : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Push() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Push() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Push(::grpc::ServerContext* /*context*/, const ::msg::PushReq* /*request*/, ::msg::PushResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPush(::grpc::ServerContext* context, ::msg::PushReq* request, ::grpc::ServerAsyncResponseWriter< ::msg::PushResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Push<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Push : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Push() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::msg::PushReq, ::msg::PushResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::msg::PushReq* request, ::msg::PushResp* response) { return this->Push(context, request, response); }));}
    void SetMessageAllocatorFor_Push(
        ::grpc::MessageAllocator< ::msg::PushReq, ::msg::PushResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::msg::PushReq, ::msg::PushResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Push() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Push(::grpc::ServerContext* /*context*/, const ::msg::PushReq* /*request*/, ::msg::PushResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Push(
      ::grpc::CallbackServerContext* /*context*/, const ::msg::PushReq* /*request*/, ::msg::PushResp* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Push<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Push : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Push() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Push() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Push(::grpc::ServerContext* /*context*/, const ::msg::PushReq* /*request*/, ::msg::PushResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Push : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Push() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Push() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Push(::grpc::ServerContext* /*context*/, const ::msg::PushReq* /*request*/, ::msg::PushResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPush(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Push : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Push() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Push(context, request, response); }));
    }
    ~WithRawCallbackMethod_Push() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Push(::grpc::ServerContext* /*context*/, const ::msg::PushReq* /*request*/, ::msg::PushResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Push(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Push : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Push() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::msg::PushReq, ::msg::PushResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::msg::PushReq, ::msg::PushResp>* streamer) {
                       return this->StreamedPush(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Push() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Push(::grpc::ServerContext* /*context*/, const ::msg::PushReq* /*request*/, ::msg::PushResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPush(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::msg::PushReq,::msg::PushResp>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Push<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Push<Service > StreamedService;
};

//     |
//     | PushReq
//     |
//     V
class GateService final {
 public:
  static constexpr char const* service_full_name() {
    return "push.GateService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Push(::grpc::ClientContext* context, const ::msg::PushReq& request, ::msg::PushResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::msg::PushResp>> AsyncPush(::grpc::ClientContext* context, const ::msg::PushReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::msg::PushResp>>(AsyncPushRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::msg::PushResp>> PrepareAsyncPush(::grpc::ClientContext* context, const ::msg::PushReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::msg::PushResp>>(PrepareAsyncPushRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Push(::grpc::ClientContext* context, const ::msg::PushReq* request, ::msg::PushResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Push(::grpc::ClientContext* context, const ::msg::PushReq* request, ::msg::PushResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::msg::PushResp>* AsyncPushRaw(::grpc::ClientContext* context, const ::msg::PushReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::msg::PushResp>* PrepareAsyncPushRaw(::grpc::ClientContext* context, const ::msg::PushReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Push(::grpc::ClientContext* context, const ::msg::PushReq& request, ::msg::PushResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::msg::PushResp>> AsyncPush(::grpc::ClientContext* context, const ::msg::PushReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::msg::PushResp>>(AsyncPushRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::msg::PushResp>> PrepareAsyncPush(::grpc::ClientContext* context, const ::msg::PushReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::msg::PushResp>>(PrepareAsyncPushRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Push(::grpc::ClientContext* context, const ::msg::PushReq* request, ::msg::PushResp* response, std::function<void(::grpc::Status)>) override;
      void Push(::grpc::ClientContext* context, const ::msg::PushReq* request, ::msg::PushResp* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::msg::PushResp>* AsyncPushRaw(::grpc::ClientContext* context, const ::msg::PushReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::msg::PushResp>* PrepareAsyncPushRaw(::grpc::ClientContext* context, const ::msg::PushReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Push_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Push(::grpc::ServerContext* context, const ::msg::PushReq* request, ::msg::PushResp* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Push : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Push() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Push() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Push(::grpc::ServerContext* /*context*/, const ::msg::PushReq* /*request*/, ::msg::PushResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPush(::grpc::ServerContext* context, ::msg::PushReq* request, ::grpc::ServerAsyncResponseWriter< ::msg::PushResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Push<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Push : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Push() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::msg::PushReq, ::msg::PushResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::msg::PushReq* request, ::msg::PushResp* response) { return this->Push(context, request, response); }));}
    void SetMessageAllocatorFor_Push(
        ::grpc::MessageAllocator< ::msg::PushReq, ::msg::PushResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::msg::PushReq, ::msg::PushResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Push() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Push(::grpc::ServerContext* /*context*/, const ::msg::PushReq* /*request*/, ::msg::PushResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Push(
      ::grpc::CallbackServerContext* /*context*/, const ::msg::PushReq* /*request*/, ::msg::PushResp* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Push<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Push : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Push() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Push() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Push(::grpc::ServerContext* /*context*/, const ::msg::PushReq* /*request*/, ::msg::PushResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Push : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Push() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Push() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Push(::grpc::ServerContext* /*context*/, const ::msg::PushReq* /*request*/, ::msg::PushResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPush(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Push : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Push() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Push(context, request, response); }));
    }
    ~WithRawCallbackMethod_Push() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Push(::grpc::ServerContext* /*context*/, const ::msg::PushReq* /*request*/, ::msg::PushResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Push(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Push : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Push() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::msg::PushReq, ::msg::PushResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::msg::PushReq, ::msg::PushResp>* streamer) {
                       return this->StreamedPush(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Push() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Push(::grpc::ServerContext* /*context*/, const ::msg::PushReq* /*request*/, ::msg::PushResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPush(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::msg::PushReq,::msg::PushResp>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Push<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Push<Service > StreamedService;
};

}  // namespace push


#endif  // GRPC_push_2eproto__INCLUDED
