// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: push.proto

#include "push.pb.h"
#include "push.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace push {

static const char* PushService_method_names[] = {
  "/push.PushService/Push",
};

std::unique_ptr< PushService::Stub> PushService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PushService::Stub> stub(new PushService::Stub(channel, options));
  return stub;
}

PushService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Push_(PushService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status PushService::Stub::Push(::grpc::ClientContext* context, const ::msg::PushReq& request, ::msg::PushResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::msg::PushReq, ::msg::PushResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Push_, context, request, response);
}

void PushService::Stub::async::Push(::grpc::ClientContext* context, const ::msg::PushReq* request, ::msg::PushResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::msg::PushReq, ::msg::PushResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Push_, context, request, response, std::move(f));
}

void PushService::Stub::async::Push(::grpc::ClientContext* context, const ::msg::PushReq* request, ::msg::PushResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Push_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::msg::PushResp>* PushService::Stub::PrepareAsyncPushRaw(::grpc::ClientContext* context, const ::msg::PushReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::msg::PushResp, ::msg::PushReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Push_, context, request);
}

::grpc::ClientAsyncResponseReader< ::msg::PushResp>* PushService::Stub::AsyncPushRaw(::grpc::ClientContext* context, const ::msg::PushReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPushRaw(context, request, cq);
  result->StartCall();
  return result;
}

PushService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PushService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PushService::Service, ::msg::PushReq, ::msg::PushResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PushService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::msg::PushReq* req,
             ::msg::PushResp* resp) {
               return service->Push(ctx, req, resp);
             }, this)));
}

PushService::Service::~Service() {
}

::grpc::Status PushService::Service::Push(::grpc::ServerContext* context, const ::msg::PushReq* request, ::msg::PushResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* GateService_method_names[] = {
  "/push.GateService/Push",
};

std::unique_ptr< GateService::Stub> GateService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< GateService::Stub> stub(new GateService::Stub(channel, options));
  return stub;
}

GateService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Push_(GateService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status GateService::Stub::Push(::grpc::ClientContext* context, const ::msg::PushReq& request, ::msg::PushResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::msg::PushReq, ::msg::PushResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Push_, context, request, response);
}

void GateService::Stub::async::Push(::grpc::ClientContext* context, const ::msg::PushReq* request, ::msg::PushResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::msg::PushReq, ::msg::PushResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Push_, context, request, response, std::move(f));
}

void GateService::Stub::async::Push(::grpc::ClientContext* context, const ::msg::PushReq* request, ::msg::PushResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Push_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::msg::PushResp>* GateService::Stub::PrepareAsyncPushRaw(::grpc::ClientContext* context, const ::msg::PushReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::msg::PushResp, ::msg::PushReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Push_, context, request);
}

::grpc::ClientAsyncResponseReader< ::msg::PushResp>* GateService::Stub::AsyncPushRaw(::grpc::ClientContext* context, const ::msg::PushReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPushRaw(context, request, cq);
  result->StartCall();
  return result;
}

GateService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GateService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GateService::Service, ::msg::PushReq, ::msg::PushResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GateService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::msg::PushReq* req,
             ::msg::PushResp* resp) {
               return service->Push(ctx, req, resp);
             }, this)));
}

GateService::Service::~Service() {
}

::grpc::Status GateService::Service::Push(::grpc::ServerContext* context, const ::msg::PushReq* request, ::msg::PushResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace push

