// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: varify.proto

#include "varify.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace varify {
PROTOBUF_CONSTEXPR GetVarifyCodeRequest::GetVarifyCodeRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.email_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.if_send_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GetVarifyCodeRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetVarifyCodeRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetVarifyCodeRequestDefaultTypeInternal() {}
  union {
    GetVarifyCodeRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetVarifyCodeRequestDefaultTypeInternal _GetVarifyCodeRequest_default_instance_;
PROTOBUF_CONSTEXPR GetVarifyCodeResponse::GetVarifyCodeResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.code_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GetVarifyCodeResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetVarifyCodeResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetVarifyCodeResponseDefaultTypeInternal() {}
  union {
    GetVarifyCodeResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetVarifyCodeResponseDefaultTypeInternal _GetVarifyCodeResponse_default_instance_;
}  // namespace varify
static ::_pb::Metadata file_level_metadata_varify_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_varify_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_varify_2eproto = nullptr;

const uint32_t TableStruct_varify_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::varify::GetVarifyCodeRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::varify::GetVarifyCodeRequest, _impl_.email_),
  PROTOBUF_FIELD_OFFSET(::varify::GetVarifyCodeRequest, _impl_.if_send_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::varify::GetVarifyCodeResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::varify::GetVarifyCodeResponse, _impl_.code_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::varify::GetVarifyCodeRequest)},
  { 8, -1, -1, sizeof(::varify::GetVarifyCodeResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::varify::_GetVarifyCodeRequest_default_instance_._instance,
  &::varify::_GetVarifyCodeResponse_default_instance_._instance,
};

const char descriptor_table_protodef_varify_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014varify.proto\022\006varify\"6\n\024GetVarifyCodeR"
  "equest\022\r\n\005email\030\001 \001(\t\022\017\n\007if_send\030\002 \001(\010\"%"
  "\n\025GetVarifyCodeResponse\022\014\n\004code\030\003 \001(\t2_\n"
  "\rVarifyService\022N\n\rGetVarifyCode\022\034.varify"
  ".GetVarifyCodeRequest\032\035.varify.GetVarify"
  "CodeResponse\"\000B\006Z\004.;pbb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_varify_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_varify_2eproto = {
    false, false, 230, descriptor_table_protodef_varify_2eproto,
    "varify.proto",
    &descriptor_table_varify_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_varify_2eproto::offsets,
    file_level_metadata_varify_2eproto, file_level_enum_descriptors_varify_2eproto,
    file_level_service_descriptors_varify_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_varify_2eproto_getter() {
  return &descriptor_table_varify_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_varify_2eproto(&descriptor_table_varify_2eproto);
namespace varify {

// ===================================================================

class GetVarifyCodeRequest::_Internal {
 public:
};

GetVarifyCodeRequest::GetVarifyCodeRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:varify.GetVarifyCodeRequest)
}
GetVarifyCodeRequest::GetVarifyCodeRequest(const GetVarifyCodeRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GetVarifyCodeRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.email_){}
    , decltype(_impl_.if_send_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.email_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.email_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_email().empty()) {
    _this->_impl_.email_.Set(from._internal_email(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.if_send_ = from._impl_.if_send_;
  // @@protoc_insertion_point(copy_constructor:varify.GetVarifyCodeRequest)
}

inline void GetVarifyCodeRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.email_){}
    , decltype(_impl_.if_send_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.email_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.email_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

GetVarifyCodeRequest::~GetVarifyCodeRequest() {
  // @@protoc_insertion_point(destructor:varify.GetVarifyCodeRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GetVarifyCodeRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.email_.Destroy();
}

void GetVarifyCodeRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GetVarifyCodeRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:varify.GetVarifyCodeRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.email_.ClearToEmpty();
  _impl_.if_send_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetVarifyCodeRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string email = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_email();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "varify.GetVarifyCodeRequest.email"));
        } else
          goto handle_unusual;
        continue;
      // bool if_send = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.if_send_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GetVarifyCodeRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:varify.GetVarifyCodeRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string email = 1;
  if (!this->_internal_email().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_email().data(), static_cast<int>(this->_internal_email().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "varify.GetVarifyCodeRequest.email");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_email(), target);
  }

  // bool if_send = 2;
  if (this->_internal_if_send() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(2, this->_internal_if_send(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:varify.GetVarifyCodeRequest)
  return target;
}

size_t GetVarifyCodeRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:varify.GetVarifyCodeRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string email = 1;
  if (!this->_internal_email().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_email());
  }

  // bool if_send = 2;
  if (this->_internal_if_send() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetVarifyCodeRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GetVarifyCodeRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetVarifyCodeRequest::GetClassData() const { return &_class_data_; }


void GetVarifyCodeRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GetVarifyCodeRequest*>(&to_msg);
  auto& from = static_cast<const GetVarifyCodeRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:varify.GetVarifyCodeRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_email().empty()) {
    _this->_internal_set_email(from._internal_email());
  }
  if (from._internal_if_send() != 0) {
    _this->_internal_set_if_send(from._internal_if_send());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GetVarifyCodeRequest::CopyFrom(const GetVarifyCodeRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:varify.GetVarifyCodeRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetVarifyCodeRequest::IsInitialized() const {
  return true;
}

void GetVarifyCodeRequest::InternalSwap(GetVarifyCodeRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.email_, lhs_arena,
      &other->_impl_.email_, rhs_arena
  );
  swap(_impl_.if_send_, other->_impl_.if_send_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetVarifyCodeRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_varify_2eproto_getter, &descriptor_table_varify_2eproto_once,
      file_level_metadata_varify_2eproto[0]);
}

// ===================================================================

class GetVarifyCodeResponse::_Internal {
 public:
};

GetVarifyCodeResponse::GetVarifyCodeResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:varify.GetVarifyCodeResponse)
}
GetVarifyCodeResponse::GetVarifyCodeResponse(const GetVarifyCodeResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GetVarifyCodeResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.code_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.code_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.code_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_code().empty()) {
    _this->_impl_.code_.Set(from._internal_code(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:varify.GetVarifyCodeResponse)
}

inline void GetVarifyCodeResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.code_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.code_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.code_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

GetVarifyCodeResponse::~GetVarifyCodeResponse() {
  // @@protoc_insertion_point(destructor:varify.GetVarifyCodeResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GetVarifyCodeResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.code_.Destroy();
}

void GetVarifyCodeResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GetVarifyCodeResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:varify.GetVarifyCodeResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.code_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetVarifyCodeResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string code = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_code();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "varify.GetVarifyCodeResponse.code"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GetVarifyCodeResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:varify.GetVarifyCodeResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string code = 3;
  if (!this->_internal_code().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_code().data(), static_cast<int>(this->_internal_code().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "varify.GetVarifyCodeResponse.code");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_code(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:varify.GetVarifyCodeResponse)
  return target;
}

size_t GetVarifyCodeResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:varify.GetVarifyCodeResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string code = 3;
  if (!this->_internal_code().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetVarifyCodeResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GetVarifyCodeResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetVarifyCodeResponse::GetClassData() const { return &_class_data_; }


void GetVarifyCodeResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GetVarifyCodeResponse*>(&to_msg);
  auto& from = static_cast<const GetVarifyCodeResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:varify.GetVarifyCodeResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_code().empty()) {
    _this->_internal_set_code(from._internal_code());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GetVarifyCodeResponse::CopyFrom(const GetVarifyCodeResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:varify.GetVarifyCodeResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetVarifyCodeResponse::IsInitialized() const {
  return true;
}

void GetVarifyCodeResponse::InternalSwap(GetVarifyCodeResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.code_, lhs_arena,
      &other->_impl_.code_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata GetVarifyCodeResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_varify_2eproto_getter, &descriptor_table_varify_2eproto_once,
      file_level_metadata_varify_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace varify
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::varify::GetVarifyCodeRequest*
Arena::CreateMaybeMessage< ::varify::GetVarifyCodeRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::varify::GetVarifyCodeRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::varify::GetVarifyCodeResponse*
Arena::CreateMaybeMessage< ::varify::GetVarifyCodeResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::varify::GetVarifyCodeResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
