// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: varify.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_varify_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_varify_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_varify_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_varify_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_varify_2eproto;
namespace varify {
class GetVarifyCodeRequest;
struct GetVarifyCodeRequestDefaultTypeInternal;
extern GetVarifyCodeRequestDefaultTypeInternal _GetVarifyCodeRequest_default_instance_;
class GetVarifyCodeResponse;
struct GetVarifyCodeResponseDefaultTypeInternal;
extern GetVarifyCodeResponseDefaultTypeInternal _GetVarifyCodeResponse_default_instance_;
}  // namespace varify
PROTOBUF_NAMESPACE_OPEN
template<> ::varify::GetVarifyCodeRequest* Arena::CreateMaybeMessage<::varify::GetVarifyCodeRequest>(Arena*);
template<> ::varify::GetVarifyCodeResponse* Arena::CreateMaybeMessage<::varify::GetVarifyCodeResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace varify {

// ===================================================================

class GetVarifyCodeRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:varify.GetVarifyCodeRequest) */ {
 public:
  inline GetVarifyCodeRequest() : GetVarifyCodeRequest(nullptr) {}
  ~GetVarifyCodeRequest() override;
  explicit PROTOBUF_CONSTEXPR GetVarifyCodeRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetVarifyCodeRequest(const GetVarifyCodeRequest& from);
  GetVarifyCodeRequest(GetVarifyCodeRequest&& from) noexcept
    : GetVarifyCodeRequest() {
    *this = ::std::move(from);
  }

  inline GetVarifyCodeRequest& operator=(const GetVarifyCodeRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetVarifyCodeRequest& operator=(GetVarifyCodeRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetVarifyCodeRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetVarifyCodeRequest* internal_default_instance() {
    return reinterpret_cast<const GetVarifyCodeRequest*>(
               &_GetVarifyCodeRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GetVarifyCodeRequest& a, GetVarifyCodeRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetVarifyCodeRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetVarifyCodeRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetVarifyCodeRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetVarifyCodeRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetVarifyCodeRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetVarifyCodeRequest& from) {
    GetVarifyCodeRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetVarifyCodeRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "varify.GetVarifyCodeRequest";
  }
  protected:
  explicit GetVarifyCodeRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEmailFieldNumber = 1,
    kIfSendFieldNumber = 2,
  };
  // string email = 1;
  void clear_email();
  const std::string& email() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_email(ArgT0&& arg0, ArgT... args);
  std::string* mutable_email();
  PROTOBUF_NODISCARD std::string* release_email();
  void set_allocated_email(std::string* email);
  private:
  const std::string& _internal_email() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_email(const std::string& value);
  std::string* _internal_mutable_email();
  public:

  // bool if_send = 2;
  void clear_if_send();
  bool if_send() const;
  void set_if_send(bool value);
  private:
  bool _internal_if_send() const;
  void _internal_set_if_send(bool value);
  public:

  // @@protoc_insertion_point(class_scope:varify.GetVarifyCodeRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr email_;
    bool if_send_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_varify_2eproto;
};
// -------------------------------------------------------------------

class GetVarifyCodeResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:varify.GetVarifyCodeResponse) */ {
 public:
  inline GetVarifyCodeResponse() : GetVarifyCodeResponse(nullptr) {}
  ~GetVarifyCodeResponse() override;
  explicit PROTOBUF_CONSTEXPR GetVarifyCodeResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetVarifyCodeResponse(const GetVarifyCodeResponse& from);
  GetVarifyCodeResponse(GetVarifyCodeResponse&& from) noexcept
    : GetVarifyCodeResponse() {
    *this = ::std::move(from);
  }

  inline GetVarifyCodeResponse& operator=(const GetVarifyCodeResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetVarifyCodeResponse& operator=(GetVarifyCodeResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetVarifyCodeResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetVarifyCodeResponse* internal_default_instance() {
    return reinterpret_cast<const GetVarifyCodeResponse*>(
               &_GetVarifyCodeResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GetVarifyCodeResponse& a, GetVarifyCodeResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetVarifyCodeResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetVarifyCodeResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetVarifyCodeResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetVarifyCodeResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetVarifyCodeResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetVarifyCodeResponse& from) {
    GetVarifyCodeResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetVarifyCodeResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "varify.GetVarifyCodeResponse";
  }
  protected:
  explicit GetVarifyCodeResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCodeFieldNumber = 3,
  };
  // string code = 3;
  void clear_code();
  const std::string& code() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_code(ArgT0&& arg0, ArgT... args);
  std::string* mutable_code();
  PROTOBUF_NODISCARD std::string* release_code();
  void set_allocated_code(std::string* code);
  private:
  const std::string& _internal_code() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_code(const std::string& value);
  std::string* _internal_mutable_code();
  public:

  // @@protoc_insertion_point(class_scope:varify.GetVarifyCodeResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_varify_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GetVarifyCodeRequest

// string email = 1;
inline void GetVarifyCodeRequest::clear_email() {
  _impl_.email_.ClearToEmpty();
}
inline const std::string& GetVarifyCodeRequest::email() const {
  // @@protoc_insertion_point(field_get:varify.GetVarifyCodeRequest.email)
  return _internal_email();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetVarifyCodeRequest::set_email(ArgT0&& arg0, ArgT... args) {
 
 _impl_.email_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:varify.GetVarifyCodeRequest.email)
}
inline std::string* GetVarifyCodeRequest::mutable_email() {
  std::string* _s = _internal_mutable_email();
  // @@protoc_insertion_point(field_mutable:varify.GetVarifyCodeRequest.email)
  return _s;
}
inline const std::string& GetVarifyCodeRequest::_internal_email() const {
  return _impl_.email_.Get();
}
inline void GetVarifyCodeRequest::_internal_set_email(const std::string& value) {
  
  _impl_.email_.Set(value, GetArenaForAllocation());
}
inline std::string* GetVarifyCodeRequest::_internal_mutable_email() {
  
  return _impl_.email_.Mutable(GetArenaForAllocation());
}
inline std::string* GetVarifyCodeRequest::release_email() {
  // @@protoc_insertion_point(field_release:varify.GetVarifyCodeRequest.email)
  return _impl_.email_.Release();
}
inline void GetVarifyCodeRequest::set_allocated_email(std::string* email) {
  if (email != nullptr) {
    
  } else {
    
  }
  _impl_.email_.SetAllocated(email, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.email_.IsDefault()) {
    _impl_.email_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:varify.GetVarifyCodeRequest.email)
}

// bool if_send = 2;
inline void GetVarifyCodeRequest::clear_if_send() {
  _impl_.if_send_ = false;
}
inline bool GetVarifyCodeRequest::_internal_if_send() const {
  return _impl_.if_send_;
}
inline bool GetVarifyCodeRequest::if_send() const {
  // @@protoc_insertion_point(field_get:varify.GetVarifyCodeRequest.if_send)
  return _internal_if_send();
}
inline void GetVarifyCodeRequest::_internal_set_if_send(bool value) {
  
  _impl_.if_send_ = value;
}
inline void GetVarifyCodeRequest::set_if_send(bool value) {
  _internal_set_if_send(value);
  // @@protoc_insertion_point(field_set:varify.GetVarifyCodeRequest.if_send)
}

// -------------------------------------------------------------------

// GetVarifyCodeResponse

// string code = 3;
inline void GetVarifyCodeResponse::clear_code() {
  _impl_.code_.ClearToEmpty();
}
inline const std::string& GetVarifyCodeResponse::code() const {
  // @@protoc_insertion_point(field_get:varify.GetVarifyCodeResponse.code)
  return _internal_code();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetVarifyCodeResponse::set_code(ArgT0&& arg0, ArgT... args) {
 
 _impl_.code_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:varify.GetVarifyCodeResponse.code)
}
inline std::string* GetVarifyCodeResponse::mutable_code() {
  std::string* _s = _internal_mutable_code();
  // @@protoc_insertion_point(field_mutable:varify.GetVarifyCodeResponse.code)
  return _s;
}
inline const std::string& GetVarifyCodeResponse::_internal_code() const {
  return _impl_.code_.Get();
}
inline void GetVarifyCodeResponse::_internal_set_code(const std::string& value) {
  
  _impl_.code_.Set(value, GetArenaForAllocation());
}
inline std::string* GetVarifyCodeResponse::_internal_mutable_code() {
  
  return _impl_.code_.Mutable(GetArenaForAllocation());
}
inline std::string* GetVarifyCodeResponse::release_code() {
  // @@protoc_insertion_point(field_release:varify.GetVarifyCodeResponse.code)
  return _impl_.code_.Release();
}
inline void GetVarifyCodeResponse::set_allocated_code(std::string* code) {
  if (code != nullptr) {
    
  } else {
    
  }
  _impl_.code_.SetAllocated(code, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.code_.IsDefault()) {
    _impl_.code_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:varify.GetVarifyCodeResponse.code)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace varify

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_varify_2eproto
